config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only:[:new, :create, :show]

  namespace :admin do
    resources :users, only:[:index, :edit, :update, :new, :create, :show, :destroy]
  end
  resources :labels
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
  has_many :task_labels, dependent: :destroy
  has_many :tasks, through: :task_labels
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional:true
  validates :title, presence:true
  validates :content, presence:true
  enum priority: [:low, :medium, :high]
  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels
  paginates_per 2
end

app/models/task_label.rb
class TaskLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :firstname , presence:true
  validates :lastname , presence:true
  validates :email , presence:true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def self.admin
    @users = User.all
    @admins = 0
    @users.each do |user|
      if user.admin?
        @admins += 1
      end
    end
    return @admins
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.order('id ASC')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'user created successfully'
    else
      render.new
    end
  end

  def show
    @tasks = Task.all
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'user details updated'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
      @admins = User.admin
    if @admins == 1
      redirect_to admin_users_path, notice: "Atleast one user or admin should remain"
#prevent not to delete logged in user
    elsif @user.id == current_user.id
        redirect_to admin_users_path, notice: "Logged in user cannot be deleted!"
    else
      @user.destroy
      redirect_to admin_users_path, notice: 'User deleted.'
    end
  end
  private

  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password,
                                 :password_confirmation, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def login_first!
    if !logged_in?
      redirect_to new_session_path, notice: "Please Login to view that page!"
    end
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]
  def index
    @labels = Label.all
  end

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(label_params)
    @label.user_id = current_user.id

    if @label.save
      redirect_to labels_path, notice: 'Label was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @label.update(label_params)
      redirect_to labels_path, notice: 'Label was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
   @label.destroy
   redirect_to labels_url, notice: 'Label was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def label_params
      params.require(:label).permit(:name, :content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to tasks_path()
    else
      flash.now[:danger] = 'Login failed! Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :login_first!

  def index
    @search = Task.ransack(params[:q])
    if params[:q]
      @tasks = @search.result.page params[:page]
    elsif params[:search_label]
    @tasks = Task.joins(:labels)
        .where("labels.name ILIKE ?", "%#{params[:search_label]}%").page params[:page]
    elsif params[:sort_deadline]
      @tasks = Task.all.order('end_at DESC').page params[:page]
    elsif params[:sort_priority]
      @tasks = Task.all.order('priority DESC').page params[:page]
    else
      @tasks = Task.all.order('created_at DESC').page params[:page]

    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :content, :status, :priority, :start_at, :end_at, :search_label, label_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = Task.all
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password,
                                 :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: @user, :url =>admin_users_path(@user), local: true) do |form| %>
  <div class="field">
    <%= form.text_field :firstname, placeholder:"First Name", class:"form-control" %>
  </div>
  <div class="field">
    <%= form.text_field :lastname, placeholder:"Last Name", class:"form-control" %>
  </div>
  <div class="field">
    <%= form.email_field :email, placeholder:"Email", class:"form-control" %>
  </div>
  <div class="field">
    <%= form.password_field :password, placeholder:"New Password", class:"form-control" %>
  </div>
  <div class="field">
    <%= form.password_field :password_coonfirmation, placeholder:"Confirm Password", class:"form-control" %>
  </div>
  <div class="field">
    <%= form.check_box :admin %> Admin
  </div>

  <div class="actions text-center mt-4">
    <%= form.submit "Save", class:"btn btn-info rounded-pill" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="mt-4 pt-5">
  <h1 class="text-center">update user details</h1>
  <div class="form-group w-25 mx-auto my-4 border rounded p-4 bg-light">

    <%= form_with(model: @user, :url =>admin_user_path(@user), local: true) do |form| %>
      <div class="field">
        <%= form.label :firstname %>
        <%= form.text_field :firstname, placeholder:"First Name", class:"form-control" %>
      </div>
      <div class="field">
        <%= form.label :lastname %>
        <%= form.text_field :lastname, placeholder:"Last Name", class:"form-control" %>
      </div>
      <div class="field">
        <%= form.label :email %>
        <%= form.email_field :email, placeholder:"Email", class:"form-control" %>
      </div>
      <div class="field">
        <%= form.label :password %>
        <%= form.password_field :password, placeholder:"New Password", class:"form-control" %>
      </div>
      <div class="field">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_coonfirmation, placeholder:"Confirm Password", class:"form-control" %>
      </div>
      <div class="field">
        <%= form.check_box :admin %> Admin
      </div>

      <div class="actions text-center mt-4">
        <%= form.submit "Save", class:"btn btn-info rounded-pill" %>
      </div>
    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<div class="mx-5">
  <div class="row">
    <div class="col-2">
      <button class="btn btn-outline-dark rounded-pill mt-5">
        <%= link_to 'Create user', new_admin_user_path %>
      </button>
    </div>
    <div class="col-8">
      <h1 class="text-center my-4">Users List</h1>
    </div>
  </div>

  <table class="table bg-light shadow-sm">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Firstname</th>
        <th scope="col">Last name</th>
        <th scope="col">Email</th>
        <th scope="col">Tasks</th>
        <th scope="col">Admin</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user, task| %>
      <tr>
        <th scope="row">
          <%= user.id %>
        </th>
        <td>
          <%= user.firstname %>
        </td>
        <td>
          <%= user.lastname %>
        </td>
        <td>
          <%= user.email %>
        </td>

        <td>
          <%= user.tasks.size%> Tasks
        </td>
        <td>
          <%= user.admin %>
        </td>
        <td class="w-25">
          <button class="btn btn-outline-info rounded-pill">
            <%= link_to 'Show', admin_user_path(user) %>
          </button>
          <button class="btn btn-outline-warning rounded-pill mx-4">
            <%= link_to 'Edit', edit_admin_user_path(user) %>
          </button>

          <button class="btn btn-outline-danger rounded-pill">
            <%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
          </button>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/new.html.erb
<div class="mt-4 pt-5">
  <h1 class="text-center">Creat user account</h1>
  <div class="form-group w-25 mx-auto my-4 border rounded p-4 bg-light">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="mx-5">
  <h1><%= @user.firstname %> <%= @user.lastname %></h1>
  <p>email address: <%= @user.email %></p>
  <h2 class="text-center">Created tasks</h2>
</div>


<% @tasks.each do |task| %>
  <% if @user.id == task.user_id %>
    <div class="mx-5 p-4 border rounded my-2 bg-light">
      <%= task.created_at.strftime("%Hh%M min %Y, %B, %d") %>
      <h5 class="my-2">
        <strong><%= task.title %></strong>
      </h5>
      <h6>This task is scheduled to start on <strong><%= task.start_at.strftime("%B, %d, %Y") %></strong> and it must end before <strong><%= task.end_at.strftime("%B, %d, %Y") %></strong><h6>
      <p class="mx-2 bg-white p-2">
        <%= task.content %>
      </p>
      <div class="row">

        <div class="col col-10">
          <!--<button class="btn btn-outline-info"><%= link_to 'Show', task %></button>
          <button class="btn btn-outline-primary"><%= link_to 'Edit', edit_task_path(task) %></button>
          <button class="btn btn-outline-danger"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        --></div>
        <div class="col">
          <p>
            <strong>Status: </strong>
            <%= task.status %><br>
            <strong>Priority:</strong>
            <%= task.priority %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id %>
  </div>
  <div class="actions">
    <%= form.submit "save"%>
  </div>
<% end %>

app/views/labels/edit.html.erb
<div class="mt-4 pt-5">
  <h1 class="text-center">Edit label</h1>
  <div class="form-group w-25 mx-auto my-4 border rounded p-4 bg-light">
    <%= render 'form', label: @label %>
  </div>
</div>

app/views/labels/index.html.erb
<div class="w-75 mx-auto text-center">

  <div class="row">
    <div class="col-2">
      <button class="btn btn-outline-dark rounded-pill mt-5">
        <%= link_to 'Create Label', new_label_path %>
      </button>
    </div>
    <div class="col-8">
      <h1 class="text-center my-4">Labels</h1>
    </div>
  </div>
<table class = "table table-bordered ">
  <thead class="bg-dark text-light">
    <tr>
      <th>Label Name</th>
      <th>User</th>
      <th colspan="3">More Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= label.user.firstname %></td>
        <td>
        <button class="btn btn-outline-info rounded-pill"><%= link_to 'Show', label %></button>
        <button class="btn btn-outline-warning rounded-pill"><%= link_to 'Edit', edit_label_path(label) %></button>
        <button class="btn btn-outline-danger rounded-pill"><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/labels/new.html.erb
<div class="mt-4 pt-5">
  <h1 class="text-center">Register a new label</h1>
  <div class="form-group w-25 mx-auto my-4 border rounded p-4 bg-light">
    <%= render 'form', label: @label %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Everyleaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <div class="bg-white">
      <% if logged_in? %>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info p-4">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a  href="#"><%= link_to 'Home', tasks_path %><span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a href="#"><%= link_to 'new task', new_task_path %></a>
              </li>
              <li class="nav-item">
                <a  href="#"><%= link_to 'Sort by deadline', tasks_path(sort_deadline: 'true') %></a>
              </li>
              <li class="nav-item">
                <a  href="#"><%= link_to 'Sort by Priority', tasks_path(sort_priority: 'true') %></a>
              </li>
              <li class="nav-item">
                <a  href="#"><%= link_to 'My page', user_path(current_user.id) %></a>
              </li>
              <li class="nav-item">
                <a  href="#"><%= link_to "User Management", admin_users_path%></a>
              </li>
              <li class="nav-item">
                <a  href="#"><%= link_to "Labels", labels_path%></a>
              </li>
              <li class="nav-item">
                <a  href="#"><%= link_to "Logout", session_path(current_user.id), method: :delete %></a>
              </li>



            </ul>

          </div>
        </nav>
      <% else %>
        <div class="bg-info p-2 text-center">
            <h1 class="text-center text-white">EVERYLEAF</h1>
        </div>
      <% end %>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>

    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, placeholder:"Title", class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, placeholder:"Content", class:"form-control" %>
  </div>
  <div class="row field">
    <%= form.label :status, class:"ml-4 mr-2" %>
    <%= form.select :status, ['Not started', 'In progress', 'Done'], class:"btn w-25" %>
  </div>

  <div class="row field">
    <%= form.label :Priority, "Priority: ", class:"ml-4" %>
    <%= form.radio_button :priority, 'low'%>Low
    <%= form.radio_button :priority, 'medium'%>Medium
    <%= form.radio_button :priority, 'high'%>High
  </div>


  <div class=" row field ml-2">
    <%= form.label :Task_start, "Task starts: ", class:"mr-2"  %>
    <%= form.date_select :start_at %>
  </div>
  <div class="row field ml-2">
    <%= form.label :Task_end, "Task ends: ", class:"mr-2"  %>
    <%= form.date_select :end_at %>
  </div>
  <b class="ml-2">Labels</b>
  <% if logged_in? %>
    <% Label.all.each do |label| %>
      <% if current_user.id == label.user_id %>
        <div class="row ml-4">
          <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
          <%= form.label:name, label.name %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <div class="actions text-center mt-4">
    <%= form.submit "Save", class:"btn btn-info " %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="mt-4 pt-5">
  <h1 class="text-center">Edit this Task</h1>
  <div class="form-group w-25 mx-auto my-4 border rounded p-4 bg-light">
  <button class="btn btn-outline-info my-2"><%= link_to 'Show', @task %></button>
    <%= render 'form', task: @task %>
    
  </div>

  
</div>

app/views/tasks/index.html.erb
<div class="mx-5 bg-white">

    <h6 class="ml-5 mt-4">All Labels</h6>
    <div class="ml-5">
      <%= form_tag(tasks_path, method: :get,style:'') do %>
  <%= text_field_tag :search_label, params[:search_label],placeholder:'  search label'%>
  <%= submit_tag '  Search', name: nil , class:"btn btn-info rounded-pill"%>
 <% end %><br>
    </div>

    <table class = "table table-bordered w-25 ml-5">
      <thead class="bg-dark text-light">
        <tr>
          <th>Label Name</th>
          <th>User</th>
        </tr>
      </thead>

      <tbody>
        <% Label.all.each do |label| %>
          <tr>
            <td><%= label.name %></td>
            <td><%= label.user.firstname %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

<hr>
<h1 class="mt-4 text-center">Available tasks</h1>
<div class="row">


<div class=" col-6  px-5">
  <%= paginate @tasks %>
</div>
<div class=" col-6  form-inline my-2 my-lg-0"><%= search_form_for @search do |f| %>
  <div class="row float-right">
    <div class="mx-4">
      <%= f.label :title_cont, "Search with title"  %>
      <%= f.text_field :title_cont, class:"field form-control mr-sm-2"%>
    </div>
    <div class>
      <div class="row">
      <div>
        <%= f.label :status_cont, "Search with status" %>
        <%= f.text_field :status_cont, class:"field form-control mr-sm-2" %>
        </div>
        <%= f.submit "Search", class:"btn btn-outline-info my-2 my-sm-0 rounded-pill"%>
      </div>
    </div>
    </div>
<% end %>
</div>
</div>

<% @tasks.each do |task| %>
  <% if logged_in? %>
    <% if current_user.id == task.user_id %>
      <div class=" p-4 border rounded my-2 bg-light">
        <%= task.created_at.strftime("%Hh%M min %Y, %B, %d") %>
        <h5 class="my-2">
          <strong><%= task.title %></strong>
        </h5>
        <h6>This task is scheduled to start on <strong><%= task.start_at.strftime("%B, %d, %Y") %></strong> and it must end before <strong><%= task.end_at.strftime("%B, %d, %Y") %></strong><h6>
        <p class="mx-2 bg-white p-2">
          <%= task.content %>
        </p>
        <div class="m-4">
          <h6>Labels</h6>
          <% task.labels.each do |label| %>
            <li class="ml-4">
            <%= label.name%>
            </li>
          <% end %>
        </div>

        <div class="row">

          <div class="col col-10">
            <button class="btn btn-outline-info"><%= link_to 'Show', task %></button>
            <button class="btn btn-outline-primary"><%= link_to 'Edit', edit_task_path(task) %></button>
            <button class="btn btn-outline-danger"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></button>
          </div>
          <div class="col">
            <p>
              <strong>Status: </strong>
              <%= task.status %><br>
              <strong>Priority:</strong>
              <%= task.priority %>
            </p>
          </div>
        </div>

      </div>
    <% end %>
  <% end %>
<% end %>
<div class="px-5"><%= paginate @tasks %></div>
</div>

app/views/tasks/new.html.erb
<div class="mt-4 pt-5">
  <h1 class="text-center">Register a new task</h1>
  <div class="form-group w-25 mx-auto my-4 border rounded p-4 bg-light">
    <%= render 'form', task: @task %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="mx-4 px-4 bg-light">
<p id="notice"><%= notice %></p>


<%= @task.created_at.strftime("%Hh%M min %Y, %B, %d") %>
<h5 class="my-2">
  <strong><%= @task.title %></strong>
</h5>
<p>This task is scheduled to start on <strong><%= @task.start_at.strftime("%B, %d, %Y") %></strong> and it must end before <strong><%= @task.end_at.strftime("%B, %d, %Y") %></strong><p>
<h6 class="mx-2 bg-white p-2">
  <%= @task.content %>
</h6>
<p>
  <strong>Status: </strong>
  <%= @task.status %><br>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>
<h6>Labels</h6>
<% @task.labels.each do |label| %>
  <li class="ml-4">
  <%= label.name%>
  </li>
<% end %>

<button class="btn btn-outline-primary"><%= link_to 'Edit', edit_task_path(@task) %></button>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |form| %>

  <div class="mt-4 pt-5">

    <div class="form-group w-25 mx-auto my-4 border rounded p-4 bg-light shadow-sm">
      <h2 class="text-center">Create your account</h2>

      <div class="field">
        <%= form.text_field :firstname, placeholder:"First Name", class:"form-control" %>
      </div>
      <div class="field">
        <%= form.text_field :lastname, placeholder:"Last Name", class:"form-control" %>
      </div>
      <div class="field">
        <%= form.email_field :email, placeholder:"Email", class:"form-control" %>
      </div>
      <div class="field">
        <%= form.password_field :password, placeholder:"New Password", class:"form-control" %>
      </div>
      <div class="field">
        <%= form.password_field :password_coonfirmation, placeholder:"Confirm Password", class:"form-control" %>
      </div>

      <div class="actions text-center mt-4">
        <%= form.submit "Signup", class:"btn btn-info rounded-pill" %>
      </div>
      <div class="field text-center">
        <p>Already a member? <b class="text-info"><%= link_to "Login", new_session_path %></b></p>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="mx-5">
  <h1><%= @user.firstname %> <%= @user.lastname %></h1>
  <p>email address: <%= @user.email %></p>
  <h2 class="text-center">Created tasks</h2>
</div>


<% @tasks.each do |task| %>
  <% if current_user.id == task.user_id %>
    <div class="mx-5 p-4 border rounded my-2 bg-light">
      <%= task.created_at.strftime("%Hh%M min %Y, %B, %d") %>
      <h5 class="my-2">
        <strong><%= task.title %></strong>
      </h5>
      <h6>This task is scheduled to start on <strong><%= task.start_at.strftime("%B, %d, %Y") %></strong> and it must end before <strong><%= task.end_at.strftime("%B, %d, %Y") %></strong><h6>
      <p class="mx-2 bg-white p-2">
        <%= task.content %>
      </p>
      <div class="row">
        <div class="col col-10">
          <button class="btn btn-outline-primary"><%= link_to 'Edit', edit_task_path(task) %></button>
          <!--<button class="btn btn-outline-info"><%= link_to 'Show', task %></button>
          <button class="btn btn-outline-danger"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        --></div>
        <div class="col">
          <p>
            <strong>Status: </strong>
            <%= task.status %><br>
            <strong>Priority:</strong>
            <%= task.priority %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>